name: slurpit
services:
  slurpit-warehouse:
    image: slurpit/warehouse@sha256:015aefe52790ea77d72b73934bf607bf57d90b4444582b4f6d792a37b7d08d23
    container_name: slurpit-warehouse
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/services"]
      interval: 10s
      timeout: 10s
      retries: 360
    networks:
      - autocon-workshop
    environment:
      TZ: Europe/Amsterdam
      WAREHOUSE_CALLBACK_SCANNER_URL: http://slurpit-portal/callback/scanner
      WAREHOUSE_CALLBACK_SCANNER_TOKEN:
      WAREHOUSE_CALLBACK_SCRAPER_URL: http://slurpit-portal/callback/scraper
      WAREHOUSE_CALLBACK_SCRAPER_TOKEN:
    volumes:
      - ./db/warehouse:/var/lib/mongodb
      - ./logs/warehouse/mongodb:/var/log/mongodb
      - ./logs/warehouse:/logs
    restart: always

  slurpit-scraper:
    image: slurpit/scraper@sha256:dc4b414cba5d99a9652576a0f458141a9af946e68357319b81c00ff3ec15a061
    container_name: slurpit-scraper
    depends_on:
      slurpit-warehouse:
        condition: service_healthy
    networks:
      - autocon-workshop
    environment:
      TZ: Europe/Amsterdam
      SCRAPER_TIMEOUT: 20
      SCRAPER_POOLSIZE: 4
      SCRAPER_WAREHOUSE_URL: http://slurpit-warehouse
    volumes:
      - ./logs/scraper:/logs
    restart: always

  slurpit-scanner:
    image: slurpit/scanner@sha256:b313c998edae561d7d74643560fb52b0c303b66e845ccbe5d7321c1daa109d60
    container_name: slurpit-scanner
    depends_on:
      slurpit-warehouse:
        condition: service_healthy
    networks:
      - autocon-workshop
    environment:
      TZ: Europe/Amsterdam
      SCANNER_POOLSIZE: 4
      SCANNER_TIMEOUT: 10
      SCANNER_WAREHOUSE_URL: http://slurpit-warehouse
    volumes:
      - ./logs/scanner:/logs
    restart: always

  slurpit-portal:
    image: slurpit/portal@sha256:4fd04895468ce2cc332561aec71609886553443647ae1cde84a1aac2ccfa00d0
    container_name: slurpit-portal
    networks:
      - autocon-workshop
    environment:
      TZ: Europe/Amsterdam
      PORTAL_BASE_URL: http://localhost
      PORTAL_WAREHOUSE_URL: http://slurpit-warehouse
    volumes:
      - ./logs/nginx:/var/log/nginx/
      - ./logs/mysql:/var/log/mysql/
      - ./logs/php:/var/log/php/
      - ./certs:/etc/nginx/certs/
      - ./db/portal:/var/lib/mysql
    restart: always

networks:
  autocon-workshop:
    external: true